# Generated by Django 3.2 on 2022-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_apartment_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='riser',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стояк'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='section',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Секция'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'section', 'floor', 'riser', 'number')},
        ),
    ]
