# Generated by Django 3.2 on 2022-09-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220912_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'section', 'floor', 'riser', 'number', 'ad')},
        ),
    ]
