# Generated by Django 3.2 on 2022-09-12 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_apartment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price_for_m2',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Цена за m2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Общая площадь'),
            preserve_default=False,
        ),
    ]
