# Generated by Django 3.2 on 2022-09-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ad_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
    ]
