# Generated by Django 3.2 on 2022-09-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_complaint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together={('user', 'type')},
        ),
    ]
