# Generated by Django 3.2 on 2022-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_filter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='status_of_house',
        ),
    ]
