# Generated by Django 3.2 on 2022-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220913_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apartments',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ads',
            field=models.ManyToManyField(blank=True, to='users.Ad', verbose_name='Избранное(Объявления)'),
        ),
    ]
