# Generated by Django 3.2 on 2022-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220913_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='apartment_layout',
            field=models.CharField(blank=True, choices=[('studio', 'Студия')], default='studio', max_length=32, null=True, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='foundation_document',
            field=models.CharField(blank=True, choices=[('property', 'Собственность')], default='property', max_length=32, null=True, verbose_name='Документ основания'),
        ),
    ]
