# Generated by Django 3.2 on 2022-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_photo_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Очередь'),
            preserve_default=False,
        ),
    ]
