# Generated by Django 3.2 on 2022-09-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220913_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ad', verbose_name='Объявление'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'section', 'floor', 'riser', 'number')},
        ),
    ]
