# Generated by Django 3.2 on 2022-09-18 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_apartment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='area_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь от'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='area_up_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площадь до'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='price_up_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена до'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ads',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='users.Ad', verbose_name='Избранное(Объявления)'),
        ),
    ]
