# Generated by Django 3.2 on 2022-08-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='document',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.house', verbose_name='ЖК'),
        ),
    ]
