# Generated by Django 3.2 on 2022-08-29 18:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gift', models.BooleanField(default=False, verbose_name='Подарок при покупке')),
                ('is_bargaining', models.BooleanField(default=False, verbose_name='Возможен торг')),
                ('is_by_the_sea', models.BooleanField(default=False, verbose_name='Квартира у моря')),
                ('is_sleeping_area', models.BooleanField(default=False, verbose_name='В спальном районе')),
                ('is_nice_price', models.BooleanField(default=False, verbose_name='Вам повезло с ценой')),
                ('is_for_big_family', models.BooleanField(default=False, verbose_name='Для большой семьи')),
                ('is_family_home', models.BooleanField(default=False, verbose_name='Семейное гнездышко')),
                ('is_private_parking', models.BooleanField(default=False, verbose_name='Отдельная парковка')),
                ('color', models.CharField(blank=True, choices=[('None', ''), ('red', 'Красный'), ('green', 'Зелёный')], default='None', max_length=32, null=True, verbose_name='Выделить цветом')),
                ('type_of_promotion', models.CharField(blank=True, choices=[('None', ''), ('big', 'Большое объявление'), ('raise', 'Поднять объявление'), ('turbo', 'Турбо')], default='None', max_length=32, null=True, verbose_name='Тип объявления')),
                ('end_date', models.DateField(default=datetime.datetime(2022, 9, 28, 18, 22, 43, 705246, tzinfo=utc), verbose_name='Дата завершения продвижения')),
            ],
            options={
                'verbose_name': 'Продвижение',
                'verbose_name_plural': 'Продвижения',
            },
        ),
    ]
