# Generated by Django 3.2 on 2022-09-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_active',
        ),
    ]
