# Generated by Django 3.2 on 2022-09-12 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_promotion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 10, 12), verbose_name='Дата завершения продвижения'),
        ),
    ]
